[package]
name = "tagless-final"
version = "0.1.0"
authors = ["Jacob Jonsson <jacob.t.jonsson@gmail.com>", "Andreas Ekeroot <andeke@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
